#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#########################

REPO="https://raw.githubusercontent.com/sasak3/v4/main/"
clear
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo -e " HR-vpn"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
clear
echo ""
  echo -e "\e[32m      ┌───────────────────────────────────────────────┐\033[0m"
  echo -e "\e[32m   ───│                                               │───\033[0m"
  echo -e "\e[32m   ───│    ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐   │───\033[0m"
  echo -e "\e[32m   ───│    ├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤    │───\033[0m"
  echo -e "\e[32m   ───│    ┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘   │───\033[0m"
  echo -e "\e[32m      │\033[0m  \e[33m      HR-vpn (C)https://t.me/HRstores      \033[0m \e[32m │\033[0m"
  echo -e "\e[32m      └───────────────────────────────────────────────┘\033[0m"
  echo -e "\e[36m             Autoscript xray vpn lite (multi port)\033[0m"
  echo -e "\e[36m  Make sure the internet is smooth when installing the script\033[0m"
  echo -e "\e[31m     JANGAN INSTALL SCRIPT INI MENGGUNAKAN KONEKSI VPN!!!\033[0m"
  echo ""
read -n 1 -s -r -p " Tekan enter untuk melanjutkan"
clear
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
On_IPurple='\033[0;105m'  #
On_IRed='\033[0;101m'
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
NC='\e[0m'

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

BURIQ () {
    curl -sS https://raw.githubusercontent.com/Andyyuda/v5/main/izin > /root/tmp
    data=( `cat /root/tmp | grep -E "^### " | awk '{print $2}'` )
    for user in "${data[@]}"
    do
    exp=( `grep -E "^### $user" "/root/tmp" | awk '{print $3}'` )
    d1=(`date -d "$exp" +%s`)
    d2=(`date -d "$biji" +%s`)
    exp2=$(( (d1 - d2) / 86400 ))
    if [[ "$exp2" -le "0" ]]; then
    echo $user > /etc/.$user.ini
    else
    rm -f /etc/.$user.ini > /dev/null 2>&1
    fi
    done
    rm -f /root/tmp
}

MYIP=$(curl -sS ipv4.icanhazip.com)
Name=$(curl -sS https://raw.githubusercontent.com/Andyyuda/v5/main/izin | grep $MYIP | awk '{print $2}')
echo $Name > /usr/local/etc/.$Name.ini
CekOne=$(cat /usr/local/etc/.$Name.ini)

Bloman () {
if [ -f "/etc/.$Name.ini" ]; then
CekTwo=$(cat /etc/.$Name.ini)
    if [ "$CekOne" = "$CekTwo" ]; then
        res="Expired"
    fi
else
res="Permission Accepted..."
fi
}

PERMISSION () {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/Andyyuda/v5/main/izin | awk '{print $4}' | grep $MYIP)
    if [ "$MYIP" = "$IZIN" ]; then
    Bloman
    else
    res="Permission Denied!"
    fi
    BURIQ
}
PERMISSION
if [ -f /home/needupdate ]; then
red "Your script need to update first !"
exit 0
elif [ "$res" = "Permission Accepted..." ]; then
echo -ne
else
red "Permission Denied!"
exit 0
fi
clear
cd /root
#System version number
if [ "${EUID}" -ne 0 ]; then
		echo "You need to run this script as root"
		exit 1
fi
if [ "$(systemd-detect-virt)" == "openvz" ]; then
		echo "OpenVZ is not supported"
		exit 1
fi

localip=$(hostname -I | cut -d\  -f1)
hst=( `hostname` )
dart=$(cat /etc/hosts | grep -w `hostname` | awk '{print $2}')
if [[ "$hst" != "$dart" ]]; then
echo "$localip $(hostname)" >> /etc/hosts
fi

mkdir -p /etc/xray
mkdir -p /etc/v2ray
touch /etc/xray/domain
touch /etc/v2ray/domain
touch /etc/xray/scdomain
touch /etc/v2ray/scdomain
echo -e "[ ${green}INFO${NC} ] Checking headers"
sleep 1
totet=`uname -r`
REQUIRED_PKG="linux-headers-$totet"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "" = "$PKG_OK" ]; then
  sleep 2
  echo -e "[ ${yell}WARNING${NC} ] Try to install ...."
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  apt-get --yes install $REQUIRED_PKG
  sleep 1
  fi

ttet=`uname -r`
ReqPKG="linux-headers-$ttet"
if ! dpkg -s $ReqPKG  >/dev/null 2>&1; then
  rm /root/setup.sh >/dev/null 2>&1 
  exit
else
  clear
fi


secs_to_human() {
    echo "Installation time : $(( ${1} / 3600 )) hours $(( (${1} / 60) % 60 )) minute's $(( ${1} % 60 )) seconds"
}
start=$(date +%s)
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null 2>&1

coreselect=''
cat> /root/.profile << END
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true
clear
END
chmod 644 /root/.profile

echo -e "[ ${green}INFO${NC} ] Preparing the install file"
apt install git curl -y >/dev/null 2>&1
apt install python -y >/dev/null 2>&1
echo -e "[ ${green}INFO${NC} ] Aight good ... installation file is ready"

mkdir -p /var/lib/SIJA >/dev/null 2>&1
echo "IP=" >> /var/lib/SIJA/ipvps.conf

echo ""
wget -q https://raw.githubusercontent.com/sasak3/v4/main/tools.sh;chmod +x tools.sh;./tools.sh
rm tools.sh
clear
#echo " "
#read -rp "Input ur domain : " -e pp
   # if [ -z $pp ]; then
   #     echo -e "
   #     Nothing input for domain!
    #    Then a random domain will be created"
   #else
   #     echo "$pp" > /root/scdomain
#	echo "$pp" > /etc/xray/scdomain
#	echo "$pp" > /etc/xray/domain
#	echo "$pp" > /etc/v2ray/domain
#	echo $pp > /root/domain
 #       echo "IP=$pp" > /var/lib/SIJA/ipvps.conf
  #  fi
  clear
echo ""
  echo -e "\e[32m      ┌───────────────────────────────────────────────┐\033[0m"
  echo -e "\e[32m   ───│                                               │───\033[0m"
  echo -e "\e[32m   ───│    ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐   │───\033[0m"
  echo -e "\e[32m   ───│    ├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤    │───\033[0m"
  echo -e "\e[32m   ───│    ┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘   │───\033[0m"
  echo -e "\e[32m      │\033[0m  \e[33m      HR-vpn (C)https://t.me/HRstores      \033[0m \e[32m │\033[0m"
  echo -e "\e[32m      └───────────────────────────────────────────────┘\033[0m"
    echo -e "${red}                ♦️ CUSTOM SETUP DOMAIN VPS ♦️   ${NC}"
    echo -e "\e[32m      ┌───────────────────────────────────────────────┐\033[0m"
    echo "          1. Gunakan Domain Dari Script"
    echo "          2. Pilih Domain Sendiri"
    echo -e "\e[32m      └───────────────────────────────────────────────┘\033[0m"
    read -rp " Tentukan domain anda : " dom 

if test $dom -eq 1; then
clear
wget -q -O /root/cf.sh "https://raw.githubusercontent.com/sasak3/v4/main/slowdns/cf.sh"
chmod +x /root/cf.sh
./cf.sh
elif test $dom -eq 2; then
read -rp "Domain/Host: " -e host
echo "IP=$host" >> /var/lib/SIJA/ipvps.conf
 "IP=$host" >> /etc/xray/domain

fi
echo -e "${GREEN}Done.${NC}"
sleep 2
clear
echo "IP=$host" >> /var/lib/SIJA/ipvps.conf
#echo "IP=$host" >> /var/lib/scrz-prem/ipvps.conf
echo "$host" >> /root/domain
#clear
wget https://raw.githubusercontent.com/sasak3/v4/main/slowdns/cfslow.sh && chmod +x cfslow.sh && ./cfslow.sh
rm -f /root/cfslow.sh
clear
wget https://raw.githubusercontent.com/heruahmad1/v4/main/tem/ssh-vpn.sh && chmod +x ssh-vpn.sh && ./ssh-vpn.sh
clear
wget https://raw.githubusercontent.com/botak8/v4/main/backup/set-br.sh &&  chmod +x set-br.sh && ./set-br.sh
clear
wget https://raw.githubusercontent.com/heruahmad1/v4/main/tem/ins-xray.sh && chmod +x ins-xray.sh && ./ins-xray.sh
wget https://raw.githubusercontent.com/sasak3/v4/main/sshws/insshws.sh && chmod +x insshws.sh && ./insshws.sh
clear
wget -q -O slow.sh https://raw.githubusercontent.com/sasak3/v4/main/slowdns/slow.sh && chmod +x slow.sh && ./slow.sh
clear
wget https://raw.githubusercontent.com/sasak3/v4/main/udp/udp.sh && bash udp.sh
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
wget -q https://raw.githubusercontent.com/heruahmad1/backupvpshrvpn/main/y.sh;chmod +x y.sh;./y.sh
rm y.sh
}
netfilter-persistent
clear
fun_bar 'res1'
clear

cat> /root/.profile << END
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true
clear
menu
END
chmod 644 /root/.profile

if [ -f "/root/log-install.txt" ]; then
rm /root/log-install.txt > /dev/null 2>&1
fi
if [ -f "/etc/afak.conf" ]; then
rm /etc/afak.conf > /dev/null 2>&1
fi
if [ ! -f "/etc/log-create-user.log" ]; then
echo "Log All Account " > /etc/log-create-user.log
fi
history -c
echo $serverV > /opt/.ver
aureb=$(cat /home/re_otm)
b=11
if [ $aureb -gt $b ]
then
gg="PM"
else
gg="AM"
fi
curl -sS ifconfig.me > /etc/myipvps
secs_to_human "$(($(date +%s) - ${start}))" | tee -a log-install.txt
rm /root/setup.sh >/dev/null 2>&1
rm /root/ins-xray.sh >/dev/null 2>&1
rm /root/insshws.sh >/dev/null 2>&1
echo -ne "[ ${yell}WARNING${NC} ] proses install selesai..."
echo -e "
"
echo -ne "[ ${yell}WARNING${NC} ] Do you want to reboot now ? (y/n)? "
read answer
if [ "$answer" == "${answer#[Yy]}" ] ;then
exit 0
else
reboot
fi
